branch-defaults:
  dev:
    environment: udacity-project-02-dev
  main:
    environment: udacity-project-02-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  udacity-project-02-dev:
    branch: null
    repository: null
global:
  application_name: udacity-project-02
  branch: main
  default_ec2_keyname: aws-eb-project-02
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
